//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clientes
    {
        public int IdCliente { get; set; }
        public string Identificacion { get; set; }
        public string NomCliente { get; set; }
        public string Ape1Cliente { get; set; }
        public string Ape2Cliente { get; set; }
        public int EstadoCliente { get; set; }
    }
}
