//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Creditos
    {
        public int CodCliente { get; set; }
        public string Operacion { get; set; }
        public Nullable<decimal> MontoOperacion { get; set; }
        public Nullable<decimal> SaldoActual { get; set; }
        public Nullable<System.DateTime> FechaFormali { get; set; }
        public Nullable<System.DateTime> FechaVenci { get; set; }
        public Nullable<System.DateTime> UltimoPago { get; set; }
        public Nullable<decimal> Tasa { get; set; }
        public Nullable<int> Plazo { get; set; }
        public Nullable<int> CuotasAtraso { get; set; }
        public Nullable<decimal> Cuota { get; set; }
    }
}
