//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InfoClientes
    {
        public int IdInfo { get; set; }
        public int CodCliente { get; set; }
        public string Institucion { get; set; }
        public Nullable<int> AnosFidelidad { get; set; }
        public Nullable<int> NumCreditos { get; set; }
        public Nullable<int> NumAhorros { get; set; }
        public Nullable<int> NumInversiones { get; set; }
        public string CatSugef { get; set; }
        public Nullable<int> CPH { get; set; }
        public Nullable<int> CPC { get; set; }
    }
}
