//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        public int CodCliente { get; set; }
        public string Producto1 { get; set; }
        public string CodProd { get; set; }
        public string DescProd { get; set; }
        public string TipoProd { get; set; }
        public Nullable<System.DateTime> FechaApertura { get; set; }
        public Nullable<System.DateTime> FechaVenci { get; set; }
        public Nullable<System.DateTime> UltimoPago { get; set; }
        public Nullable<decimal> SaldoActual { get; set; }
        public Nullable<decimal> IntAcum { get; set; }
        public Nullable<decimal> Tasa { get; set; }
        public Nullable<int> Periocidad { get; set; }
        public Nullable<int> PLAZO { get; set; }
        public Nullable<int> Cupones { get; set; }
        public Nullable<int> CuotasAtraso { get; set; }
        public Nullable<decimal> Cuota { get; set; }
    }
}
